management:
  metrics:
    web:
      server:
        auto-time-requests: true
  health :
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details : never
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
      base-path: /internal/actuator
springdoc:
  api-docs:
    path: /internal/api-docs
  swagger-ui:
    path: /internal/swagger
  version: 1.0
nav:
  navn : '@project.artifactId@'
  versjon : '@project.version@'
  beskrivelse : '@project.description@'

no.nav:
  saf:
    base_url: ${SAF_BASE_URL}
    scopes:
      hente_journalpost_scopes: ${SAF_HENTE_JOURNALPOST_SCOPES:foo,bar}
      hente_dokument_scopes: ${SAF_HENTE_DOKUMENT_SCOPES:foo,bar}
  security.jwt:
    expirythreshold: 1
    client:
      azure:
        client_id: ${AZURE_client_id}
        jwk: ${AZURE_jwk}
        token_endpoint: ${AZURE_token_endpoint}
    issuer:
      azurev1:
        discoveryurl: ${AZURE_V1_discovery_url}
        accepted_audience: ${AZURE_client_id}
      azurev2:
        discoveryurl: ${AZURE_V2_discovery_url}
        accepted_audience: ${AZURE_client_id}