management:
  metrics:
    web:
      server:
        auto-time-requests: true
  health :
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details : never
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
      base-path: /internal/actuator
springdoc:
  api-docs:
    path: /internal/api-docs
  swagger-ui:
    path: /internal/swagger
  version: 1.0
nav:
  navn : '@project.artifactId@'
  versjon : '@project.version@'
  beskrivelse : '@project.description@'