name: Build & deploy to dev-gcp

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Bygge JAR
        run: mvn clean package --settings ./.m2/settings.xml
        env:
          GITHUB_PASSWORD: ${{ secrets.READER_TOKEN }}

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: k9saksbehandling
          push_image: true
          pull: true
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/naiserator.yml
          VARS: nais/dev-gcp.yml
          IMAGE: ${{ steps.docker-push.outputs.image }}
