name: Vulnerabilities scanning of dependencies
on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.READER_TOKEN }}
        with:
          command: monitor
          args: --org=k9saksbehandling --configuration-attributes=usage:java-runtime --all-projects --remote-repo-url=https://github.com/${{ github.repository }}.git -- -s .m2/settings.xml
